
/// <summary>
/// Interface for objects that can be inserted into a Pool.
/// </summary>
/// <example>
/// public class TestObject : MonoBehaviour, IPoolable
/// {
///		public void OnGenerate() { }
///		public void OnCheckout() { }
///		public void OnRelease() { }
/// }
/// </example>
public interface IPoolable
{
	/// <summary>
	/// Called only when this poolable is generated by a pool (not for objects in the scene)
	/// </summary>
	void OnGenerate();

	/// <summary>
	/// Called when this object is checked out from a pool
	/// </summary>
	void OnCheckout();

	/// <summary>
	/// Called when this object is released, and returned to the pool
	/// </summary>
	void OnRelease();
}